TitleService/TitleClient/Models/TitleModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TitleService.Models
{
    public partial class TitleModel
    {
        [DisplayAttribute(Name = "Title Id")]
        public int TitleId { get; set; }

        [DisplayAttribute(Name = "Title Name")]
        public string TitleName { get; set; }

        [DisplayAttribute(Name = "Sortable")]
        public string TitleNameSortable { get; set; }

        [DisplayAttribute(Name = "Title Type Id")]
        [DisplayFormat(NullDisplayText="Title TypeId not specified")]
        public int?TitleTypeId { get; set; }

        [DisplayAttribute(Name = "Release Year")]
        public int?ReleaseYear { get; set; }

        [DisplayAttribute(Name = "Processed DateTime")]
        public DateTime?ProcessedDateTimeUTC { get; set; }

    }
}

TitleService/TitleClient/Models/TitleModel.designer.cs
// Default code generation is disabled for model 'C:\SRIKANTH\srikanth\Projects\TitleService\TitleService\Models\Title.edmx'. 
// To enable default code generation, change the value of the 'Code Generation Strategy' designer
// property to an alternate value. This property is available in the Properties Window when the model is
// open in the designer.

TitleService/TitleClient/Controllers/TitleClientController.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web.Mvc;
using TitleService.Models;
using PagedList;
using System.Linq;
using System.Collections;
using System.Threading.Tasks;

namespace TitleClient.Controllers
{
    public class TitleClientController : Controller
    {
        //
        // GET: /TitleClient/
        private static IEnumerable<TitleModel> titleModel;
        [OutputCache(Duration=20)]
        public async Task<ActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "TitleName" : "";
            ViewBag.DateSortParm = sortOrder == "ReleaseYear" ? "ReleaseYear)" : "ReleaseYear";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            

            titleModel = new List<TitleModel>();
            HttpClient client =  new HttpClient();
            client.BaseAddress = new Uri(@"http://localhost:4374/");

            client.DefaultRequestHeaders.Accept.Add(
                new MediaTypeWithQualityHeaderValue("application/json"));

            HttpResponseMessage response = await client.GetAsync("api/title");
            if (response.IsSuccessStatusCode)
            {
                titleModel =  response.Content.ReadAsAsync<List<TitleModel>>().Result;
            }

            if (!string.IsNullOrWhiteSpace(Request.QueryString["TitleName"]))
            {
                searchString=Request.QueryString["TitleName"].ToString();
            }

            List<TitleModel> listTitleModel =  titleModel.ToList();
            if (!String.IsNullOrEmpty(searchString))
            {
                ViewBag.CurrentFilter = searchString;
                titleModel =  listTitleModel.OfType<TitleModel>().Where (titleName => titleName.TitleName.ToUpper().Contains(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "TitleName":
                    titleModel = titleModel.OrderByDescending(s => s.TitleName);
                    break;
                case "ReleaseYear":
                    titleModel = titleModel.OrderByDescending(s => s.ReleaseYear);
                    break;
                default:
                    titleModel = titleModel.OrderBy(s => s.TitleName);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(titleModel.ToPagedList(pageNumber, pageSize));
            //return View(titleModel);
        }
        
        //
        // GET: /TitleClient/Details/5

        public ActionResult Details(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TitleModel titleDetail = GetTitle(name);

            return View(titleDetail);
        }

        public static TitleModel GetTitle(string name)
        {
            return titleModel.ToList().Find(m => m.TitleName== name);
        }

    }
}

TitleService/TitleClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

TitleService/TitleClient/Views/TitleClient/Details.cshtml
@model TitleService.Models.TitleModel

@{
    ViewBag.Title = "Details";
}

<section class="featured">
    <div class="content-wrapper">

        <hgroup class="title">
            <h1>@ViewBag.Title</h1>
        </hgroup>
    </div>
    <div class="content-table">
        <table>
            <tr>
                <td>
                    <span class="label">@Html.DisplayNameFor(model => model.TitleName) </span>
                </td>
                <td>
                    @Html.DisplayFor(model => model.TitleName)
                </td>
            </tr>
            <tr>
                <td>
                    <span class="label">@Html.DisplayNameFor(model => model.TitleId) : </span>
                </td>
                <td>
                    @Html.DisplayFor(model => model.TitleId)
                </td>
            </tr>
            <tr>
                <td>
                    <span class="label">@Html.DisplayNameFor(model => model.TitleNameSortable) : </span>
                </td>
                <td>
                    @Html.DisplayFor(model => model.TitleNameSortable)
                </td>
            </tr>
            <tr>
                <td>
                    <span class="label">@Html.DisplayNameFor(model => model.TitleTypeId) : </span>
                </td>
                <td>
                    @Html.DisplayFor(model => model.TitleTypeId)
                </td>
            </tr>
            <tr>
                <td>
                    <span class="label">@Html.DisplayNameFor(model => model.ReleaseYear) : </span>
                </td>
                <td>
                    @Html.DisplayFor(model => model.ReleaseYear)
                </td>
            </tr>
            <tr>
                <td>
                    <span class="label">@Html.DisplayNameFor(model => model.ProcessedDateTimeUTC) : </span>
                </td>
                 <td>
                    @Html.DisplayFor(model => model.ProcessedDateTimeUTC)
                </td>
                
            </tr>
        </table>

        <p>
            <span class="backlist">@Html.ActionLink("Back to List", "Index") </span>
        </p>
    </div>
</section>

TitleService/TitleClient/Views/TitleClient/Details.mobile.cshtml
@model TitleService.Models.TitleModel

@{
    ViewBag.Title = "Details";
}

<section class="featured">
    <div class="content-wrapper">

        <hgroup class="title">
            <h1>@ViewBag.Title</h1>
        </hgroup>
    </div>
    <div class="content-table">
        <table>
            <tr>
                <td>
                    <span class="label">@Html.DisplayNameFor(model => model.TitleName) </span>
                </td>
                <td>
                    @Html.DisplayFor(model => model.TitleName)
                </td>
            </tr>
            <tr>
                <td>
                    <span class="label">@Html.DisplayNameFor(model => model.TitleId) : </span>
                </td>
                <td>
                    @Html.DisplayFor(model => model.TitleId)
                </td>
            </tr>
            <tr>
                <td>
                    <span class="label">@Html.DisplayNameFor(model => model.TitleNameSortable) : </span>
                </td>
                <td>
                    @Html.DisplayFor(model => model.TitleNameSortable)
                </td>
            </tr>
            <tr>
                <td>
                    <span class="label">@Html.DisplayNameFor(model => model.TitleTypeId) : </span>
                </td>
                <td>
                    @Html.DisplayFor(model => model.TitleTypeId)
                </td>
            </tr>
            <tr>
                <td>
                    <span class="label">@Html.DisplayNameFor(model => model.ReleaseYear) : </span>
                </td>
                <td>
                    @Html.DisplayFor(model => model.ReleaseYear)
                </td>
            </tr>
            <tr>
                <td>
                    <span class="label">@Html.DisplayNameFor(model => model.ProcessedDateTimeUTC) : </span>
                </td>
                 <td>
                    @Html.DisplayFor(model => model.ProcessedDateTimeUTC)
                </td>
                
            </tr>
        </table>

        <p>
            <span class="backlist">@Html.ActionLink("Back to List", "Index") </span>
        </p>
    </div>
</section>

TitleService/TitleClient/Views/TitleClient/Index .android.cshtml
@model PagedList.IPagedList<TitleService.Models.TitleModel>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />


@{
    ViewBag.Title = "Titles";
}


<section class="featured">
    <div class="content-wrapper">

        <hgroup class="title">
            <h1>@ViewBag.Title</h1>
            
        </hgroup>
        </div>
    </section>
<div class="content-table">

@using (Html.BeginForm("Index", "TitleClient", FormMethod.Get))
{
    <p>
        Find by Title name : @Html.TextBox("TitleName", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>
        <th class="sort first">
            @Html.ActionLink("TitleName", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th class="first">
            Title ID
        </th>
        <th class="sort first">
            @Html.ActionLink("ReleaseYear", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter } )
        </th>
        <th></th>
    </tr>


    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TitleName)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.TitleId)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseYear)
            </td>
            
            <td>
                @Html.ActionLink("Details", "Details", new { name = item.TitleName })
            </td>
        </tr>
    }

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
    </div>

TitleService/TitleClient/Views/TitleClient/Index .mobile.cshtml
@model PagedList.IPagedList<TitleService.Models.TitleModel>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />


@{
    ViewBag.Title = "Titles";
}


<section class="featured">
    <div class="content-wrapper">

        <hgroup class="title">
            <h1>@ViewBag.Title</h1>
            
        </hgroup>
        </div>
    </section>
<div class="content-table">

@using (Html.BeginForm("Index", "TitleClient", FormMethod.Get))
{
    <p>
        Find by Title name : @Html.TextBox("TitleName", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>
        <th class="sort first">
            @Html.ActionLink("TitleName", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th class="first">
            Title ID
        </th>
        <th class="sort first">
            @Html.ActionLink("ReleaseYear", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter } )
        </th>
        <th></th>
    </tr>


    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TitleName)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.TitleId)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseYear)
            </td>
            
            <td>
                @Html.ActionLink("Details", "Details", new { name = item.TitleName })
            </td>
        </tr>
    }

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
    </div>

TitleService/TitleClient/Views/TitleClient/Index.cshtml
@model PagedList.IPagedList<TitleService.Models.TitleModel>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />


@{
    ViewBag.Title = "Titles";
}


<section class="featured">
    <div class="content-wrapper">

        <hgroup class="title">
            <h1>@ViewBag.Title</h1>
            
        </hgroup>
        </div>
    </section>
<div class="content-table">

@using (Html.BeginForm("Index", "TitleClient", FormMethod.Get))
{
    <p>
        Find by Title name : @Html.TextBox("TitleName", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>
        <th class="sort first">
            @Html.ActionLink("Title Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th class="first">
            Title ID
        </th>
        <th class="sort first">
            @Html.ActionLink("Release Year", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter } )
        </th>
        <th></th>
    </tr>


    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayNameFor(modelItem => item.TitleName)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.TitleId)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseYear)
            </td>
            
            <td>
                @Html.ActionLink("Details", "Details", new { name = item.TitleName })
            </td>
        </tr>
    }

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
    </div>